name: Build Container Images
run-name: ${{ github.actor }} is building container images 🚀
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  Build-Latest-Container:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Get osbuild rpm version
        id: get-osbuild-rpm-version
        run: |
          sudo apt update
          sudo apt install dnf
          export LATEST_VERSION
          LATEST_VERSION=$(dnf repoquery \
            --repofrompath "osbuild,https://download.copr.fedorainfracloud.org/results/%40osbuild/osbuild/fedora-36-x86_64" \
            --repoid=osbuild \
            --queryformat="%{EPOCH}:%{VERSION}-%{RELEASE}" \
            osbuild.noarch)
          echo "LATEST_VERSION=${LATEST_VERSION}"
          echo "::set-output name=osbuild_version::${LATEST_VERSION}"
          echo "::set-output name=container_tag::$(echo ${LATEST_VERSION} | tr : .)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: michael131468/osbuild-docker:${{ steps.get-osbuild-rpm-version.outputs.container_tag }} , michael131468/osbuild-docker:latest
          file: Containerfile
          build-args: VERSION=-${{ steps.get-osbuild-rpm-version.outputs.osbuild_version }}
